channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - dtw-python
  - pysoundfile
  - kaldi
  - transformers
  - pytorch
  - scipy>=1.9.0
  - pip:
    - pika>=1.3.0
